import type {
  BetPreview,
  DashboardNavItem,
  GamePreview,
  HomeRunPick,
  InjuryReport,
  KpiMetric,
  OddsRow,
  PitcherProp,
  PlayerProp,
  TrendRow,
  WeatherReport,
} from "@/src/types/mlb-dashboard";

export const dashboardNavItems: DashboardNavItem[] = [
  { active: true, href: "#dashboard", icon: "⌂", label: "Dashboard" },
  { href: "#slate", icon: "◆", label: "Today's Slate" },
  { href: "#best-bets", icon: "↗", label: "Best Bets" },
  { href: "#player-props", icon: "◎", label: "Player Props" },
  { href: "#pitcher-props", icon: "K", label: "Pitcher Props" },
  { href: "#home-run-model", icon: "◇", label: "Home Run Model" },
  { href: "#team-trends", icon: "▦", label: "Team Trends" },
  { href: "#odds", icon: "±", label: "Odds" },
  { href: "#injuries", icon: "!", label: "Injuries" },
  { href: "#weather", icon: "☁", label: "Weather" },
  { href: "#settings", icon: "⚙", label: "Settings" },
];

export const kpiMetrics: KpiMetric[] = [
  { label: "Games Today", meta: "Full MLB slate", value: "15" },
  { label: "Best Overall Bet", meta: "Dodgers ML -118", value: "+6.2%" },
  { label: "Highest EV Bet", meta: "Rangers TT over 4.5", value: "+4.7%" },
  { label: "Top Pitcher Prop", meta: "Wheeler over 6.5 Ks", value: "82" },
  { label: "Top Home Run Pick", meta: "Aaron Judge +285", value: "18.4%" },
];

export const games: GamePreview[] = [
  {
    awayTeam: "Dodgers",
    confidence: "78",
    homeTeam: "Braves",
    moneyline: "LAD -118 / ATL +100",
    spread: "LAD -1.5 (+142)",
    starters: "Yamamoto vs Strider",
    time: "7:20 PM ET",
    total: "8.0",
    weatherIcon: "Clear",
  },
  {
    awayTeam: "Yankees",
    confidence: "73",
    homeTeam: "Red Sox",
    moneyline: "NYY -104 / BOS -112",
    spread: "NYY -1.5 (+158)",
    starters: "Cole vs Bello",
    time: "7:10 PM ET",
    total: "8.5",
    weatherIcon: "Wind out",
  },
  {
    awayTeam: "Phillies",
    confidence: "71",
    homeTeam: "Mets",
    moneyline: "PHI +102 / NYM -120",
    spread: "PHI +1.5 (-184)",
    starters: "Wheeler vs Senga",
    time: "6:40 PM ET",
    total: "7.5",
    weatherIcon: "Cloudy",
  },
  {
    awayTeam: "Rangers",
    confidence: "76",
    homeTeam: "Astros",
    moneyline: "TEX +116 / HOU -136",
    spread: "TEX +1.5 (-170)",
    starters: "Eovaldi vs Valdez",
    time: "8:10 PM ET",
    total: "9.0",
    weatherIcon: "Roof likely",
  },
];

export const topBets: BetPreview[] = [
  {
    betType: "Moneyline",
    confidence: "78",
    edge: "+6.2%",
    modelProjection: "-133",
    player: "Dodgers",
    recommendedUnits: "1.25u",
    sportsbookLine: "-118",
  },
  {
    betType: "Team Total",
    confidence: "76",
    edge: "+5.4%",
    modelProjection: "5.3 runs",
    player: "Rangers",
    recommendedUnits: "1.10u",
    sportsbookLine: "Over 4.5",
  },
  {
    betType: "Strikeouts",
    confidence: "82",
    edge: "+7.1%",
    modelProjection: "7.4 Ks",
    player: "Zack Wheeler",
    recommendedUnits: "1.00u",
    sportsbookLine: "Over 6.5",
  },
  {
    betType: "Total Bases",
    confidence: "75",
    edge: "+5.9%",
    modelProjection: "2.1 TB",
    player: "Mookie Betts",
    recommendedUnits: "0.90u",
    sportsbookLine: "Over 1.5",
  },
  {
    betType: "Hits Allowed",
    confidence: "74",
    edge: "+4.8%",
    modelProjection: "4.7 H",
    player: "Logan Gilbert",
    recommendedUnits: "0.85u",
    sportsbookLine: "Under 5.5",
  },
  {
    betType: "Home Run",
    confidence: "69",
    edge: "+4.5%",
    modelProjection: "18.4%",
    player: "Aaron Judge",
    recommendedUnits: "0.45u",
    sportsbookLine: "+285",
  },
  {
    betType: "RBI",
    confidence: "72",
    edge: "+4.2%",
    modelProjection: "0.71 RBI",
    player: "Austin Riley",
    recommendedUnits: "0.70u",
    sportsbookLine: "Over 0.5",
  },
  {
    betType: "Walks",
    confidence: "70",
    edge: "+3.9%",
    modelProjection: "1.0 BB",
    player: "Juan Soto",
    recommendedUnits: "0.60u",
    sportsbookLine: "Over 0.5",
  },
  {
    betType: "Earned Runs",
    confidence: "71",
    edge: "+3.7%",
    modelProjection: "2.4 ER",
    player: "Brayan Bello",
    recommendedUnits: "0.55u",
    sportsbookLine: "Under 2.5",
  },
  {
    betType: "Moneyline",
    confidence: "68",
    edge: "+3.4%",
    modelProjection: "+118",
    player: "Padres",
    recommendedUnits: "0.50u",
    sportsbookLine: "+136",
  },
];

export const homeRunPicks: HomeRunPick[] = [
  {
    ballpark: "Fenway Park",
    hrProbability: "18.4%",
    pitcher: "Brayan Bello",
    player: "Aaron Judge",
    valueRating: "A-",
    wind: "Out to LF 12 mph",
  },
  {
    ballpark: "Truist Park",
    hrProbability: "16.9%",
    pitcher: "Spencer Strider",
    player: "Shohei Ohtani",
    valueRating: "B+",
    wind: "Out to RF 7 mph",
  },
  {
    ballpark: "Minute Maid Park",
    hrProbability: "14.8%",
    pitcher: "Framber Valdez",
    player: "Adolis Garcia",
    valueRating: "B",
    wind: "Roof likely closed",
  },
];

export const playerProps: PlayerProp[] = [
  {
    confidence: "75",
    edge: "+5.9%",
    line: "Over 1.5 total bases",
    player: "Mookie Betts",
    projection: "2.1 TB",
    propType: "Total Bases",
  },
  {
    confidence: "72",
    edge: "+4.2%",
    line: "Over 0.5 RBI",
    player: "Austin Riley",
    projection: "0.71 RBI",
    propType: "RBI",
  },
  {
    confidence: "70",
    edge: "+3.9%",
    line: "Over 0.5 walks",
    player: "Juan Soto",
    projection: "1.0 BB",
    propType: "Walks",
  },
];

export const pitcherProps: PitcherProp[] = [
  {
    confidence: "82",
    edge: "+7.1%",
    opponentKRate: "24.8%",
    pitcher: "Zack Wheeler",
    projection: "7.4 Ks",
    vegasLine: "6.5",
  },
  {
    confidence: "79",
    edge: "+5.8%",
    opponentKRate: "25.6%",
    pitcher: "George Kirby",
    projection: "6.3 Ks",
    vegasLine: "5.5",
  },
  {
    confidence: "74",
    edge: "+4.6%",
    opponentKRate: "22.9%",
    pitcher: "Logan Gilbert",
    projection: "6.0 Ks",
    vegasLine: "5.5",
  },
  {
    confidence: "70",
    edge: "+3.5%",
    opponentKRate: "23.5%",
    pitcher: "Gerrit Cole",
    projection: "6.8 Ks",
    vegasLine: "6.5",
  },
];

export const weatherReports: WeatherReport[] = [
  {
    environment: "Hitter Friendly",
    rainChance: "8%",
    stadium: "Fenway Park",
    temperature: "78°F",
    windDirection: "Out to LF",
    windSpeed: "12 mph",
  },
  {
    environment: "Neutral",
    rainChance: "15%",
    stadium: "Truist Park",
    temperature: "82°F",
    windDirection: "Out to RF",
    windSpeed: "7 mph",
  },
  {
    environment: "Pitcher Friendly",
    rainChance: "4%",
    stadium: "Citi Field",
    temperature: "70°F",
    windDirection: "In from CF",
    windSpeed: "10 mph",
  },
  {
    environment: "Neutral",
    rainChance: "0%",
    stadium: "Minute Maid Park",
    temperature: "74°F",
    windDirection: "Roof likely closed",
    windSpeed: "0 mph",
  },
];

export const injuries: InjuryReport[] = [
  { expectedReturn: "Day-to-day", player: "Freddie Freeman", status: "Questionable", team: "LAD" },
  { expectedReturn: "Late June", player: "Ozzie Albies", status: "10-day IL", team: "ATL" },
  { expectedReturn: "Tonight", player: "Juan Soto", status: "Probable", team: "NYY" },
  { expectedReturn: "TBD", player: "Rafael Devers", status: "Questionable", team: "BOS" },
  { expectedReturn: "Next series", player: "Jose Altuve", status: "Day-to-day", team: "HOU" },
  { expectedReturn: "July", player: "Jacob deGrom", status: "15-day IL", team: "TEX" },
  { expectedReturn: "Day-to-day", player: "Pete Alonso", status: "Probable", team: "NYM" },
  { expectedReturn: "Late June", player: "Bryce Harper", status: "Questionable", team: "PHI" },
];

export const teamTrends: TrendRow[] = [
  { label: "Dodgers", note: "Top-3 xwOBA over last 14 days", value: "+12.4%" },
  { label: "Rangers", note: "Hard-hit rate rising against LHP", value: "+8.1%" },
  { label: "Mets", note: "Bullpen leverage arms taxed", value: "High" },
  { label: "Red Sox", note: "Home park run environment elevated", value: "112" },
];

export const oddsRows: OddsRow[] = [
  { bestPrice: "-118", market: "Dodgers ML", move: "+9 cents", open: "-127" },
  { bestPrice: "O 4.5 -105", market: "Rangers TT", move: "-4 cents", open: "O 4.5 -101" },
  { bestPrice: "O 6.5 +104", market: "Wheeler Ks", move: "+6 cents", open: "O 6.5 -102" },
  { bestPrice: "+285", market: "Judge HR", move: "+18 cents", open: "+267" },
];
