import type {
  BetPreview,
  DashboardNavItem,
  GamePreview,
  InjuryReport,
  KpiMetric,
  PlayerProp,
  PropCategory,
  SlateMeta,
  WeatherReport,
} from "@/src/types/mlb-dashboard";

export const slateMeta: SlateMeta = {
  averageConfidence: "74%",
  currentDate: "Monday, June 22",
  firstPitchCountdown: "2h 18m",
  gamesToday: 6,
  lastUpdated: "11:42 AM ET",
};

export const dashboardNavItems: DashboardNavItem[] = [
  { active: true, href: "#daily-slate", icon: "⌂", label: "Slate", badge: "6" },
  { href: "#games", icon: "◆", label: "Games", badge: "6" },
  { href: "#best-bets", icon: "↗", label: "Best Bets", badge: "10" },
  { href: "#player-props", icon: "◎", label: "Props" },
  { href: "#weather", icon: "☁", label: "Weather", badge: "3" },
  { href: "#injuries", icon: "!", label: "Injuries" },
];

export const kpiMetrics: KpiMetric[] = [
  { label: "Games Today", meta: "Primary slate markets", value: "6", tone: "blue" },
  {
    label: "Highest Confidence Bet",
    meta: "Wheeler over 6.5 Ks",
    value: "84%",
    tone: "emerald",
  },
  {
    label: "Highest EV Bet",
    meta: "Dodgers ML -118",
    value: "+6.4%",
    tone: "emerald",
  },
  {
    label: "Best Pitcher Prop",
    meta: "Zack Wheeler Ks",
    value: "+7.1%",
    tone: "blue",
  },
  {
    label: "Best Home Run Pick",
    meta: "Aaron Judge +285",
    value: "18.4%",
    tone: "amber",
  },
  {
    label: "Avg Model Confidence",
    meta: "Across top signals",
    value: "74%",
    tone: "blue",
  },
];

export const games: GamePreview[] = [
  {
    awayPitcher: "Yoshinobu Yamamoto",
    awayTeam: "Dodgers",
    confidence: 78,
    detail: "Dodgers grade stronger in bullpen availability and late-game contact quality.",
    gameTime: "7:20 PM ET",
    homePitcher: "Spencer Strider",
    homeTeam: "Braves",
    moneyline: "LAD -118 / ATL +100",
    spread: "LAD -1.5 (+142)",
    status: "Confirmed",
    total: "8.0",
    venue: "Truist Park",
    weather: "82F, wind out to RF 7 mph",
  },
  {
    awayPitcher: "Gerrit Cole",
    awayTeam: "Yankees",
    confidence: 73,
    detail: "Run environment is elevated, but New York owns the cleaner relief path.",
    gameTime: "7:10 PM ET",
    homePitcher: "Brayan Bello",
    homeTeam: "Red Sox",
    moneyline: "NYY -104 / BOS -112",
    spread: "NYY -1.5 (+158)",
    status: "Weather Watch",
    total: "8.5",
    venue: "Fenway Park",
    weather: "78F, wind out to LF 12 mph",
  },
  {
    awayPitcher: "Zack Wheeler",
    awayTeam: "Phillies",
    confidence: 76,
    detail: "Wheeler projects for the slate's best strikeout ceiling against an aggressive order.",
    gameTime: "6:40 PM ET",
    homePitcher: "Kodai Senga",
    homeTeam: "Mets",
    moneyline: "PHI +102 / NYM -120",
    spread: "PHI +1.5 (-184)",
    status: "Confirmed",
    total: "7.5",
    venue: "Citi Field",
    weather: "70F, wind in from CF 10 mph",
  },
  {
    awayPitcher: "Nathan Eovaldi",
    awayTeam: "Rangers",
    confidence: 75,
    detail: "Texas has the best team-total gap on the board if the roof stays closed.",
    gameTime: "8:10 PM ET",
    homePitcher: "Framber Valdez",
    homeTeam: "Astros",
    moneyline: "TEX +116 / HOU -136",
    spread: "TEX +1.5 (-170)",
    status: "Roof Watch",
    total: "9.0",
    venue: "Minute Maid Park",
    weather: "Roof likely closed, neutral air",
  },
  {
    awayPitcher: "George Kirby",
    awayTeam: "Mariners",
    confidence: 72,
    detail: "Kirby gains value from a high chase-rate opponent and a pitcher-friendly setup.",
    gameTime: "9:38 PM ET",
    homePitcher: "Reid Detmers",
    homeTeam: "Angels",
    moneyline: "SEA -126 / LAA +108",
    spread: "SEA -1.5 (+132)",
    status: "Line Watch",
    total: "8.0",
    venue: "Angel Stadium",
    weather: "68F, marine layer settling in",
  },
  {
    awayPitcher: "Joe Musgrove",
    awayTeam: "Padres",
    confidence: 69,
    detail: "Market is shading San Francisco too heavily for a low-total divisional game.",
    gameTime: "9:45 PM ET",
    homePitcher: "Logan Webb",
    homeTeam: "Giants",
    moneyline: "SD +136 / SF -162",
    spread: "SD +1.5 (-152)",
    status: "Confirmed",
    total: "7.0",
    venue: "Oracle Park",
    weather: "61F, wind across 14 mph",
  },
];

export const topBets: BetPreview[] = [
  {
    bet: "Over 6.5 strikeouts",
    confidence: 84,
    edge: "+7.1%",
    modelProjection: "7.4 Ks",
    player: "Zack Wheeler",
    reasoning: "The Mets' projected lineup carries the highest chase gap on the slate.",
    recommendedUnits: "1.15u",
    sportsbookLine: "+104",
  },
  {
    bet: "Moneyline",
    confidence: 80,
    edge: "+6.4%",
    modelProjection: "-134",
    player: "Dodgers",
    reasoning: "Los Angeles rates better in bullpen rest and late-inning matchup leverage.",
    recommendedUnits: "1.20u",
    sportsbookLine: "-118",
  },
  {
    bet: "Over 4.5 team runs",
    confidence: 77,
    edge: "+5.6%",
    modelProjection: "5.3 runs",
    player: "Rangers",
    reasoning: "Texas has a strong platoon edge if Houston keeps the roof closed.",
    recommendedUnits: "1.00u",
    sportsbookLine: "-105",
  },
  {
    bet: "Over 1.5 total bases",
    confidence: 76,
    edge: "+5.4%",
    modelProjection: "2.2 TB",
    player: "Mookie Betts",
    reasoning: "Betts owns the best contact-quality profile against Strider's fastball mix.",
    recommendedUnits: "0.90u",
    sportsbookLine: "-110",
  },
  {
    bet: "Home run",
    confidence: 72,
    edge: "+4.9%",
    modelProjection: "18.4%",
    player: "Aaron Judge",
    reasoning: "Fenway wind adds carry to Judge's highest-probability pull-air profile.",
    recommendedUnits: "0.45u",
    sportsbookLine: "+285",
  },
  {
    bet: "Under 5.5 hits allowed",
    confidence: 72,
    edge: "+4.7%",
    modelProjection: "4.7 H",
    player: "Logan Gilbert",
    reasoning: "San Francisco's contact model falls below market expectation in cold air.",
    recommendedUnits: "0.70u",
    sportsbookLine: "-118",
  },
  {
    bet: "Over 0.5 RBI",
    confidence: 71,
    edge: "+4.4%",
    modelProjection: "0.71 RBI",
    player: "Austin Riley",
    reasoning: "Riley sits in the highest run-creation slot for Atlanta's implied total.",
    recommendedUnits: "0.65u",
    sportsbookLine: "+125",
  },
  {
    bet: "Over 0.5 runs",
    confidence: 70,
    edge: "+4.1%",
    modelProjection: "0.76 R",
    player: "Julio Rodriguez",
    reasoning: "Seattle's top order projects for added traffic against Detmers early.",
    recommendedUnits: "0.55u",
    sportsbookLine: "-102",
  },
  {
    bet: "Moneyline",
    confidence: 69,
    edge: "+3.8%",
    modelProjection: "+118",
    player: "Padres",
    reasoning: "The model prices this as closer to a coin-flip than the market suggests.",
    recommendedUnits: "0.50u",
    sportsbookLine: "+136",
  },
  {
    bet: "Under 2.5 earned runs",
    confidence: 68,
    edge: "+3.5%",
    modelProjection: "2.1 ER",
    player: "George Kirby",
    reasoning: "Kirby's command profile limits free passes against a thin Angels lineup.",
    recommendedUnits: "0.45u",
    sportsbookLine: "-108",
  },
];

export const propCategories: Array<{ label: PropCategory; props: PlayerProp[] }> = [
  {
    label: "Strikeouts",
    props: [
      {
        category: "Strikeouts",
        confidence: 84,
        edge: "+7.1%",
        line: "Over 6.5",
        player: "Zack Wheeler",
        projection: "7.4 Ks",
        reasoning: "Elite swing-and-miss gap against the Mets' projected bottom half.",
        team: "PHI",
      },
      {
        category: "Strikeouts",
        confidence: 79,
        edge: "+5.8%",
        line: "Over 5.5",
        player: "George Kirby",
        projection: "6.3 Ks",
        reasoning: "Angels lineup projects below average against command-first righties.",
        team: "SEA",
      },
    ],
  },
  {
    label: "Hits",
    props: [
      {
        category: "Hits",
        confidence: 74,
        edge: "+4.6%",
        line: "Over 0.5",
        player: "Freddie Freeman",
        projection: "1.18 H",
        reasoning: "Stable contact profile against high-velocity four-seam usage.",
        team: "LAD",
      },
      {
        category: "Hits",
        confidence: 71,
        edge: "+3.9%",
        line: "Over 0.5",
        player: "Corey Seager",
        projection: "1.09 H",
        reasoning: "Line-drive rate remains elevated versus sinker-heavy lefties.",
        team: "TEX",
      },
    ],
  },
  {
    label: "Runs",
    props: [
      {
        category: "Runs",
        confidence: 70,
        edge: "+4.1%",
        line: "Over 0.5",
        player: "Julio Rodriguez",
        projection: "0.76 R",
        reasoning: "Leadoff plate appearances add volume in Seattle's top stack.",
        team: "SEA",
      },
      {
        category: "Runs",
        confidence: 69,
        edge: "+3.7%",
        line: "Over 0.5",
        player: "Shohei Ohtani",
        projection: "0.72 R",
        reasoning: "Dodgers' implied total keeps Ohtani's scoring path live.",
        team: "LAD",
      },
    ],
  },
  {
    label: "RBI",
    props: [
      {
        category: "RBI",
        confidence: 71,
        edge: "+4.4%",
        line: "Over 0.5",
        player: "Austin Riley",
        projection: "0.71 RBI",
        reasoning: "Premium lineup slot behind Atlanta's best on-base cluster.",
        team: "ATL",
      },
      {
        category: "RBI",
        confidence: 68,
        edge: "+3.6%",
        line: "Over 0.5",
        player: "Adolis Garcia",
        projection: "0.66 RBI",
        reasoning: "Garcia benefits from Texas' strongest team-total edge.",
        team: "TEX",
      },
    ],
  },
  {
    label: "Home Runs",
    props: [
      {
        category: "Home Runs",
        confidence: 72,
        edge: "+4.9%",
        line: "+285",
        player: "Aaron Judge",
        projection: "18.4%",
        reasoning: "Fenway wind lifts the best pull-side power profile in the slate.",
        team: "NYY",
      },
      {
        category: "Home Runs",
        confidence: 67,
        edge: "+3.3%",
        line: "+360",
        player: "Shohei Ohtani",
        projection: "15.1%",
        reasoning: "Ohtani's barrel rate keeps him live despite a tougher pitcher matchup.",
        team: "LAD",
      },
    ],
  },
  {
    label: "Total Bases",
    props: [
      {
        category: "Total Bases",
        confidence: 76,
        edge: "+5.4%",
        line: "Over 1.5",
        player: "Mookie Betts",
        projection: "2.2 TB",
        reasoning: "Betts grades highest in hard-contact probability against Atlanta.",
        team: "LAD",
      },
      {
        category: "Total Bases",
        confidence: 73,
        edge: "+4.2%",
        line: "Over 1.5",
        player: "Juan Soto",
        projection: "2.0 TB",
        reasoning: "Soto's patience creates extra-base upside against Bello's mistakes.",
        team: "NYY",
      },
    ],
  },
];

export const weatherReports: WeatherReport[] = [
  {
    game: "Yankees at Red Sox",
    hitterFriendlyRating: 88,
    humidity: "58%",
    pitcherFriendlyRating: 32,
    rainChance: "18%",
    stadium: "Fenway Park",
    temperature: "78F",
    windDirection: "Out to LF",
    windSpeed: "12 mph",
  },
  {
    game: "Dodgers at Braves",
    hitterFriendlyRating: 76,
    humidity: "64%",
    pitcherFriendlyRating: 41,
    rainChance: "15%",
    stadium: "Truist Park",
    temperature: "82F",
    windDirection: "Out to RF",
    windSpeed: "7 mph",
  },
  {
    game: "Phillies at Mets",
    hitterFriendlyRating: 36,
    humidity: "51%",
    pitcherFriendlyRating: 82,
    rainChance: "4%",
    stadium: "Citi Field",
    temperature: "70F",
    windDirection: "In from CF",
    windSpeed: "10 mph",
  },
  {
    game: "Rangers at Astros",
    hitterFriendlyRating: 55,
    humidity: "Indoor",
    pitcherFriendlyRating: 56,
    rainChance: "0%",
    stadium: "Minute Maid Park",
    temperature: "74F",
    windDirection: "Roof likely closed",
    windSpeed: "0 mph",
  },
];

export const injuries: InjuryReport[] = [
  {
    expectedReturn: "Day-to-day",
    impactRating: 82,
    player: "Freddie Freeman",
    status: "Questionable",
    team: "LAD",
  },
  {
    expectedReturn: "Late June",
    impactRating: 76,
    player: "Ozzie Albies",
    status: "10-day IL",
    team: "ATL",
  },
  {
    expectedReturn: "Tonight",
    impactRating: 68,
    player: "Juan Soto",
    status: "Probable",
    team: "NYY",
  },
  {
    expectedReturn: "Game-time decision",
    impactRating: 73,
    player: "Rafael Devers",
    status: "Questionable",
    team: "BOS",
  },
  {
    expectedReturn: "Next series",
    impactRating: 63,
    player: "Jose Altuve",
    status: "Day-to-day",
    team: "HOU",
  },
  {
    expectedReturn: "July",
    impactRating: 88,
    player: "Jacob deGrom",
    status: "15-day IL",
    team: "TEX",
  },
  {
    expectedReturn: "Available",
    impactRating: 61,
    player: "Pete Alonso",
    status: "Probable",
    team: "NYM",
  },
  {
    expectedReturn: "Late June",
    impactRating: 79,
    player: "Bryce Harper",
    status: "Questionable",
    team: "PHI",
  },
];
