export const routes = {
  home: "/",
  bestBets: "#best-bets",
  dashboard: "#dashboard",
  homeRunModel: "#home-run-model",
  injuries: "#injuries",
  odds: "#odds",
  pitcherProps: "#pitcher-props",
  playerProps: "#player-props",
  pitcherResearch: "/pitcher-research",
  settings: "#settings",
  slate: "#slate",
  teamTrends: "#team-trends",
  weather: "#weather",
} as const;
