export const MATCHUP_INTELLIGENCE_CONFIG = {
  cacheTtlSeconds: 86400,
  componentWeights: {
    contact: 0.25,
    expectedDamage: 0.25,
    movement: 0.2,
    velocity: 0.15,
    zone: 0.15,
  },
  confidenceWeights: {
    arsenalQuality: 0.3,
    batterQuality: 0.25,
    contextQuality: 0.05,
    playerIntelligenceAvailability: 0.1,
    recentMatchup: 0.15,
    zoneAvailability: 0.15,
  },
  contactWeights: {
    batterWhiffWeakness: 0.45,
    pitchWhiffStrength: 0.55,
  },
  contextDefaults: {
    availableContextQuality: 75,
    neutralScore: 50,
    unavailableContextQuality: 50,
  },
  movementWeights: {
    horizontal: 0.45,
    vertical: 0.55,
  },
  overallWeights: {
    ballpark: 0.08,
    bullpen: 0.06,
    pitchType: 0.42,
    recentForm: 0.18,
    weather: 0.08,
    zone: 0.18,
  },
  recentWeights: {
    consistency: 0.2,
    recentForm: 0.65,
    trends: 0.15,
  },
  ranges: {
    averageExitVelocityMph: { high: 94, low: 84 },
    barrelPercent: { high: 18, low: 3 },
    chaseZonePercent: { high: 32, low: 12 },
    horizontalBreakInches: { high: 16, low: 2 },
    inZonePercent: { high: 62, low: 42 },
    isolatedPower: { high: 0.28, low: 0.08 },
    velocityMph: { high: 99, low: 82 },
    verticalBreakInches: { high: 18, low: 2 },
    whiffPercent: { high: 40, low: 15 },
    zoneDamageRating: { high: 80, low: 20 },
  },
  thresholds: {
    advantageScore: 62,
    coldZoneDamage: 40,
    favorableOverall: 65,
    hotZoneDamage: 65,
    limitedWhiffPercent: 18,
    maxRecentConfidenceBonus: 35,
    playerIntelligenceUnavailableConfidence: 35,
    recentConfidenceBase: 45,
    recentConfidencePerLog: 4,
    primaryPitchUsagePercent: 30,
    zoneAvailableConfidence: 80,
    zoneUnavailableConfidence: 45,
    riskyOverall: 40,
    riskScore: 42,
    trendImpactPoints: 8,
  },
} as const;
