export const RANKING_ENGINE_CONFIG = {
  confidenceTiers: {
    elite: 85,
    high: 72,
    medium: 55,
  },
  explanationThresholds: {
    bullpenAdvantage: 65,
    confidence: 78,
    dataQuality: 78,
    edge: 4,
    expectedValue: 3,
    lineupCertainty: 70,
    lowVariance: 35,
    matchup: 72,
    recentForm: 70,
    weather: 65,
  },
  gradeThresholds: [
    { grade: "A+", score: 92 },
    { grade: "A", score: 86 },
    { grade: "A-", score: 80 },
    { grade: "B+", score: 74 },
    { grade: "B", score: 68 },
    { grade: "B-", score: 62 },
    { grade: "C+", score: 56 },
    { grade: "C", score: 50 },
    { grade: "D", score: 42 },
    { grade: "F", score: 0 },
  ],
  recommendationThresholds: {
    elite: 88,
    lean: 58,
    play: 70,
    strongPlay: 80,
  },
  riskTiers: {
    high: 68,
    low: 34,
  },
  scoreWeights: {
    bullpenImpact: 0.06,
    confidence: 0.14,
    dataQuality: 0.12,
    edge: 0.18,
    expectedValue: 0.18,
    lineupCertainty: 0.05,
    marketRisk: 0.05,
    matchupStrength: 0.1,
    recentForm: 0.06,
    variance: 0.03,
    weatherImpact: 0.03,
  },
} as const;
